version: '3.9'

services:
  postgres:
    image: postgres:14.6
    restart: always
    ports:
      # - '5432:5432'
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # mongo       ->    /data/db
      # mysql       ->    /var/lib/mysql
      # postgres    ->    /var/lib/postgresql/data



  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '80:80'


    # Connection: localhost:80
      # host: postgres
      # user: postgres
      # pass: .env